# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{table_to_model}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Stefan Penner"]
  s.date = %q{2010-09-26}
  s.default_executable = %q{table_to_model}
  s.description = %q{Using an ActiveRecord connection this tool generates the corresponding models }
  s.email = %q{stefan.penner@gmail.com}
  s.executables = ["table_to_model"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/table_to_model.rb",
     "lib/templates/model.tt",
     "lib/templates/model_in_module.tt",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/table_to_model_spec.rb"
  ]
  s.homepage = %q{http://github.com/stefanpenner/table_to_model}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Generate models from a databases tables from an Active Record Connection}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/table_to_model_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_runtime_dependency(%q<thor>, ["= 0.14.2"])
      s.add_runtime_dependency(%q<activerecord>, ["= 3.0.0"])
      s.add_runtime_dependency(%q<activesupport>, ["= 3.0.0"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<thor>, ["= 0.14.2"])
      s.add_dependency(%q<activerecord>, ["= 3.0.0"])
      s.add_dependency(%q<activesupport>, ["= 3.0.0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<thor>, ["= 0.14.2"])
    s.add_dependency(%q<activerecord>, ["= 3.0.0"])
    s.add_dependency(%q<activesupport>, ["= 3.0.0"])
  end
end

